### ISSUE TITLE
use generic deployment

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/gw-backend#6]

**Comment by volodymyrss** [comment]
maybe instead would be better to make some sort of general tool, not chart for each.

**Comment by dsavchenko** [comment]
@volodymyrss Any developments from your side for the general tool from your side?
Have you deployed to the testing environment in some general way already?

**Comment by volodymyrss** [comment]
I deployed. But no sharable development. Till  the end of the month - I probably will not manage.

**Comment by dsavchenko** [comment]
Does it make sense to develop something from my side in parallel? Or just create separate charts for now?

**Comment by volodymyrss** [comment]
> Does it make sense to develop something from my side in parallel? Or just create separate charts for now?

Since it seems I am not going to do it till Jan 31, give it a try if you want! This is potentially reusable, so it's good to not duplicate very similar chart. So either a tool that deploys directly, or some chart generator could be useful. Or other ideas a welcome!

**Comment by volodymyrss** [comment]
done
