### ISSUE TITLE
let's create renku repository with these notebooks

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/gw-backend#7]

**Comment by dsavchenko** [comment]
See https://renkulab.io/gitlab/dsavchenko/gw-backend

There is, however, an error in CI/CD there `InvalidVersionSpec: Invalid version '3.2<5.0.0': invalid character(s)`
@volodymyrss  you know how to fix

**Comment by dsavchenko** [comment]
BTW, error in gw190425 is expected. There are no H1 data for some reason https://www.gw-openscience.org/eventapi/html/GWTC-2.1-confident/GW190425/v3

**Comment by volodymyrss** [comment]
Ok, cool, thanks. it's deployed.
